import type { DateRange, DistrictFilters, LeaderboardPeriod, LeaderboardScope } from '@/types';

/** Centralised query keys — invalidation stays consistent across features. */
export const qk = {
  me: ['me'] as const,
  student: {
    all: ['student'] as const,
    dashboard: ['student', 'dashboard'] as const,
    quests: ['student', 'quests'] as const,
    achievements: ['student', 'achievements'] as const,
    badges: ['student', 'badges'] as const,
    certificates: ['student', 'certificates'] as const,
    assignments: ['student', 'assignments'] as const,
    exams: ['student', 'exams'] as const,
    leaderboard: (scope: LeaderboardScope, period: LeaderboardPeriod) => ['student', 'leaderboard', scope, period] as const,
    recommendations: ['student', 'recommendations'] as const,
    settings: ['student', 'settings'] as const,
  },
  world: ['world'] as const,
  wallet: ['wallet'] as const,
  avatar: ['avatar'] as const,
  avatarItems: (category?: string) => ['avatar', 'items', category ?? 'all'] as const,
  course: (id: string) => ['course', id] as const,
  lesson: (courseId: string, lessonId: string) => ['lesson', courseId, lessonId] as const,
  quiz: (id: string) => ['quiz', id] as const,
  ai: { history: ['ai', 'history'] as const },
  parent: {
    children: ['parent', 'children'] as const,
    dashboard: (childId: string | undefined, range: DateRange) => ['parent', 'dashboard', childId ?? 'default', range] as const,
    progress: (childId: string) => ['parent', 'progress', childId] as const,
    activity: (childId: string) => ['parent', 'activity', childId] as const,
    assessments: (childId: string) => ['parent', 'assessments', childId] as const,
    achievements: (childId: string) => ['parent', 'achievements', childId] as const,
  },
  teacher: {
    dashboard: (range: DateRange) => ['teacher', 'dashboard', range] as const,
    classes: ['teacher', 'classes'] as const,
    class: (id: string) => ['teacher', 'class', id] as const,
    students: (search: string, classId?: string) => ['teacher', 'students', search, classId ?? ''] as const,
    student: (id: string) => ['teacher', 'student', id] as const,
    assignments: ['teacher', 'assignments'] as const,
    quizzes: ['teacher', 'quizzes'] as const,
    analytics: (classId?: string) => ['teacher', 'analytics', classId ?? 'all'] as const,
  },
  school: {
    dashboard: (range: DateRange) => ['school', 'dashboard', range] as const,
    students: (search: string) => ['school', 'students', search] as const,
    teachers: (search: string) => ['school', 'teachers', search] as const,
    classes: ['school', 'classes'] as const,
    courses: (status?: string) => ['school', 'courses', status ?? 'all'] as const,
    analytics: (range: DateRange) => ['school', 'analytics', range] as const,
  },
  district: {
    dashboard: (f: DistrictFilters) => ['district', 'dashboard', f] as const,
    schools: (search: string) => ['district', 'schools', search] as const,
    school: (id: string) => ['district', 'school', id] as const,
    students: (search: string) => ['district', 'students', search] as const,
    teachers: (search: string) => ['district', 'teachers', search] as const,
    analytics: (f: DistrictFilters) => ['district', 'analytics', f] as const,
  },
  notifications: ['notifications'] as const,
};
